# https://docs.github.com/en/actions/creating-actions/creating-a-composite-action

on:
  workflow_dispatch:
#  push:
#    branches:
#      - main

jobs:
# MS Teams notification
  notify:
    runs-on: ubuntu-latest
    name: Notify
    if: always()
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Hello world action step
        uses: ./
        with:
          environment: "TEST"
          app_version: ${{ needs.setup.outputs.app_version }}
          commit_short_sha: ${{ needs.setup.outputs.commit_short_sha }}
          committer_name: ${{ needs.setup.outputs.committer_name }}
          commit_message: ${{ needs.setup.outputs.commit_message }}
          committer_email: ${{ needs.setup.outputs.committer_email }}
        secrets:
          webhook_url: ${{ secrets.MSTEAMS_DEBUG }}
